name: 'Delete Release & Tag'
description: 'Delete release and corresponding tag by tag name'
inputs:
    tag_name:
        description: 'Tag name'
        required: true
        default: 'issue-1234'
runs:
    using: 'node12'
    main: 'index.js'
